# Generated by Django 5.0.6 on 2026-04-25 17:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code (e.g., US, UK, AU)', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 characters)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_url', models.URLField(help_text='Source URL from OpportunityDesk', unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('Scholarship', 'Scholarship'), ('Internship', 'Internship'), ('Fellowship', 'Fellowship'), ('Assistantship', 'Assistantship'), ('Grant', 'Grant'), ('Competition', 'Competition'), ('Event', 'Conference / Workshop / Seminar'), ('Job', 'Job Opportunity'), ('Other', 'Other')], default='Scholarship', max_length=50)),
                ('funding_type', models.CharField(choices=[('Fully Funded', 'Fully Funded'), ('Partial Funding', 'Partial Funding'), ('Tuition Fee Waiver', 'Tuition Fee Waiver'), ('Stipend Only', 'Stipend Only'), ('Unpaid', 'Unpaid')], default='Partial Funding', max_length=50)),
                ('funding_amount', models.CharField(blank=True, help_text='e.g., $5000, Full Tuition', max_length=255)),
                ('provides_stipend', models.BooleanField(default=False)),
                ('stipend_amount', models.CharField(blank=True, help_text='e.g., $1500 monthly living allowance', max_length=255)),
                ('deadline_type', models.CharField(choices=[('Specific Date', 'Specific Date'), ('Varies by Country', 'Varies by Country'), ('Rolling', 'Rolling / Continuous'), ('Always Open', 'Always Open')], default='Specific Date', max_length=50)),
                ('deadline', models.DateField(blank=True, help_text='Leave blank if Rolling or Varies by Country', null=True)),
                ('deadline_note', models.CharField(blank=True, help_text="e.g. '11:59 PM CET'", max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('official_link', models.URLField(help_text='Link to the official provider', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunity_images')),
                ('meta_title', models.CharField(blank=True, help_text='Keep under 60 chars.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Keep under 160 chars.', max_length=160)),
                ('focus_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('image_alt_text', models.CharField(blank=True, max_length=125)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='blog.category')),
                ('education_levels', models.ManyToManyField(related_name='opportunities', to='blog.educationlevel')),
                ('host_countries', models.ManyToManyField(blank=True, related_name='hosted_opportunities', to='blog.country')),
                ('target_countries', models.ManyToManyField(blank=True, related_name='targeted_opportunities', to='blog.country')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
