# Generated by Django 5.2.5 on 2025-12-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_guide_meta_description_guide_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='deadline',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline_type',
            field=models.CharField(choices=[('fixed', 'Fixed Deadline'), ('rolling', 'Rolling Basis'), ('country_wise', 'Country-wise Deadline'), ('tba', 'To Be Announced')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='primary_deadline',
            field=models.DateField(blank=True, help_text='Main deadline (used for sorting & SEO)', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.CharField(help_text='e.g. Full Tuition, $5,000, Monthly Stipend', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoctoral', 'Postdoctoral'), ('short_course', 'Short Course'), ('online_course', 'Online Course'), ('all_levels', 'All Levels')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='official_link',
            field=models.URLField(help_text='Official application link'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('scholarship', 'Scholarship'), ('fully_funded_scholarship', 'Fully Funded Scholarship'), ('partial_scholarship', 'Partial Scholarship'), ('internship', 'Internship'), ('paid_internship', 'Paid Internship'), ('remote_internship', 'Remote Internship'), ('summer_internship', 'Summer Internship'), ('fellowship', 'Fellowship'), ('assistantship', 'Assistantship'), ('grant', 'Grant'), ('conference', 'Conference'), ('summer_school', 'Summer School'), ('exchange_program', 'Exchange Program'), ('training_program', 'Training Program'), ('leadership_program', 'Leadership Program'), ('job', 'Job Opportunity'), ('volunteer', 'Volunteer Program'), ('other', 'Other')], default='scholarship', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='target_countries',
            field=models.CharField(help_text='e.g. Nepal, USA, India, All Countries', max_length=255),
        ),
    ]
