# Generated by Django 5.2.5 on 2025-12-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_opportunity_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='deadline_type',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='primary_deadline',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(default='2099-12-31'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline_note',
            field=models.CharField(blank=True, help_text="e.g. '11:59 PM CET'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.CharField(help_text='e.g., $5000 or Full Tuition', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('Pre-University', 'Pre-University'), ('Undergraduate', 'Undergraduate'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Doctoral', 'Doctoral'), ('Postdoctoral', 'Postdoctoral'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Short Course', 'Short Course'), ('Online Course', 'Online Course'), ('Professional Course', 'Professional Course'), ('Early Career', 'Early Career'), ('Mid Career', 'Mid Career'), ('All Levels', 'All Levels')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='official_link',
            field=models.URLField(help_text='Link to the official provider'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('Scholarship', 'Scholarship'), ('Fully Funded Scholarship', 'Fully Funded Scholarship'), ('Partial Scholarship', 'Partial Scholarship'), ('Internship', 'Internship'), ('Paid Internship', 'Paid Internship'), ('Remote Internship', 'Remote Internship'), ('Summer Internship', 'Summer Internship'), ('Fellowship', 'Fellowship'), ('Research Fellowship', 'Research Fellowship'), ('Postdoctoral Fellowship', 'Postdoctoral Fellowship'), ('Assistantship', 'Assistantship'), ('Teaching Assistantship', 'Teaching Assistantship'), ('Research Assistantship', 'Research Assistantship'), ('Grant', 'Grant'), ('Research Grant', 'Research Grant'), ('Startup Grant', 'Startup Grant'), ('Competition', 'Competition'), ('Hackathon', 'Hackathon'), ('Essay Competition', 'Essay Competition'), ('Case Competition', 'Case Competition'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Summer School', 'Summer School'), ('Exchange Program', 'Exchange Program'), ('Training Program', 'Training Program'), ('Leadership Program', 'Leadership Program'), ('Bootcamp', 'Bootcamp'), ('Job Opportunity', 'Job Opportunity'), ('Volunteer Program', 'Volunteer Program'), ('Travel Grant', 'Travel Grant'), ('Fully Funded Program', 'Fully Funded Program'), ('Other', 'Other')], default='Scholarship', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='target_countries',
            field=models.CharField(help_text='Countries eligible for this', max_length=255),
        ),
    ]
