# Generated by Django 5.2.5 on 2025-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_opportunity_deadline_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(),
        ),
    ]
