# Generated by Django 5.2.5 on 2026-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_opportunity_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
