# Generated by Django 5.2.5 on 2026-01-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_opportunity_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='logo_url',
        ),
    ]
