# Generated by Django 5.2.5 on 2026-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_opportunity_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_url', models.URLField(help_text='Source URL from OpportunityDesk', unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
